export const SET_WHITELISTED_ASSET = "SET_WHITELISTED_ASSET";
export const SET_ALL_WHITELISTED_ASSET = "SET_ALL_WHITELISTED_ASSET";
export const SET_ISLOCKER_EXIST = "SET_ISLOCKER_EXIST";
export const SET_USER_LOCKED_VALUE = "SET_USER_LOCKED_VALUE";
export const SET_SLIDER_TOOLTIP_VISIBLE = "SET_SLIDER_TOOLTIP_VISIBLE";