export const tabsList = [
  // {
  //   name: "Dashboard",
  //   value: "dashboard",
  //   langKey: "dashboard",
  //   path: "dashboard",
  //   active: "dashboard",
  //   index: 0,
  // },
  {
    name: "My Positions",
    value: "home",
    langKey: "positions",
    path: "myPositions",
    active: "myPositions",
    index: 1,
  },
  {
    name: "Assets",
    value: "assets",
    langKey: "assets",
    path: "assets",
    active: "assets",
    index: 2,
  },
  // {
  //   name: "stable Mint",
  //   value: "borrow",
  //   langKey: "stableMint",
  //   path: "stableMint",
  //   active: "stableMint",
  //   index: 3,
  // },
  {
    name: "mint",
    value: "borrow",
    langKey: "mint",
    path: "mint",
    active: "mint",
    index: 3,
    className: "disable",
  },
  {
    name: "govern",
    value: "govern",
    langKey: "govern",
    path: "govern",
    active: "govern",
    index: 4,
  },
  {
    name: "auction",
    value: "auction-icon",
    langKey: "auction",
    path: "auctions",
    active: "auctions",
    index: 5,
  },
  {
    name: "emission",
    value: "emission-icon",
    langKey: "emission",
    path: "emission",
    active: "emission",
    index: 6,
  },
  {
    name: "stake",
    value: "stake-icon",
    langKey: "stake",
    path: "stake",
    active: "stake",
    index: 7,
  },
  {
    name: "rewards",
    value: "reward-icon",
    langKey: "rewards",
    path: "rewards",
    active: "rewards",
    index: 8,
  },
  {
    name: "locker",
    value: "locker-icon",
    langKey: "locker",
    path: "locker",
    active: "locker",
    index: 9,
  },

  {
    name: "bridge",
    value: "bridge-icon",
    langKey: "bridge",
    path: "bridge",
    active: "bridge",
    index: 10,
  },
];
