export const tabsList = [
  {
    name: "Dashboard",
    value: "dashboard",
    langKey: "dashboard",
    path: "dashboard",
    active: "dashboard",
    index: 0,
  },
  {
    name: "My Positions",
    value: "home",
    langKey: "positions",
    path: "my-positions",
    active: "my-positions",
    index: 1,
  },
  {
    name: "Assets",
    value: "assets",
    langKey: "assets",
    path: "assets",
    active: "assets",
    index: 2,
  },
  {
    name: "stable Mint",
    value: "borrow",
    langKey: "stableMint",
    path: "stableMint",
    active: "stableMint",
    index: 3,
  },
  {
    name: "mint",
    value: "borrow",
    langKey: "mint",
    path: "mint",
    active: "mint",
    index: 4,
    className: "disable",
  },
  {
    name: "auction",
    value: "auction-icon",
    langKey: "auction",
    path: "auctions",
    active: "auctions",
    index: 5,
  },
  {
    name: "govern",
    value: "govern",
    langKey: "govern",
    path: "govern",
    active: "govern",
    index: 6,
  },
  {
    name: "more",
    value: "more",
    langKey: "more",
    path: "more",
    active: "more",
    index: 7,
  },
];
