export const tabsList = [
  {
    name: "Dashboard",
    value: "dashboard",
    langKey: "dashboard",
    path: "dashboard",
    active: "dashboard",
    index: 0,
  },
  {
    name: "My Positions",
    value: "home",
    langKey: "positions",
    path: "myPositions",
    active: "myPositions",
    index: 2,
  },
  {
    name: "borrow",
    value: "borrow",
    langKey: "borrow",
    path: "borrow",
    active: "borrow",
    index: 3,
  },
  {
    name: "earn",
    value: "earn",
    langKey: "earn",
    path: "earn",
    active: "earn",
    index: 4,
  },
  {
    name: "auction",
    value: "auction",
    langKey: "auction",
    path: "auctions",
    active: "auctions",
    index: 5,
  },
];
